seed_contracts:
  - "0x0C9a3dd6b8F28529d72d7f9cE918D493519EE383"
  - "0x8Ff1C814719096b61aBf00Bb46EAd0c9A529Dd7D"
  - "0x29a56a1b8214D9Cf7c5561811750D5cBDb45CC8e"
  - "0x000000000022D473030F116dDEE9F6B43aC78BA3"
  - "0x4cD6BF1D183264c02Be7748Cb5cd3A47d013351b"
  - "0xEADDD21618ad5Deb412D3fD23580FD461c106B54"
  - "0x0D52d06ceB8Dcdeeb40Cfd9f17489B350dD7F8a3"
  - "0x9a20d3c0c283646e9701a049a2f8c152bc1e3427"
  - "0xBa42141648dFD74388f3541C1d80fa9387043Da9"

blacklist_contracts:
  - "0x1F98431c8aD98523631AE4a59f267346ea31F984"  # Uniswap

name_blacklist_regex: "(?i)tether" 

num_transactions: 10
max_depth: 1


tenderly_credentials:
  user: "your_user"
  project: "your_project"
  access_key: "<REDACTED>"

etherscan_api_key: "<REDACTED>"

deployer_discovery_scope: "seed_only"
